/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedAgenciaIndexRouteImport } from './routes/_authenticated/agencia.index'
import { Route as AuthenticatedAgenciaClientesRouteImport } from './routes/_authenticated/agencia.clientes'
import { Route as AuthenticatedAgenciaEquipeRouteImport } from './routes/_authenticated/agencia.equipe'
import { Route as AuthenticatedAgenciaFluxoRouteImport } from './routes/_authenticated/agencia.fluxo'
import { Route as AuthenticatedAgenciaVisualizarRouteImport } from './routes/_authenticated/agencia.visualizar'
import { Route as AuthenticatedAgenciaAutomacoesIndexRouteImport } from './routes/_authenticated/agencia.automacoes.index'
import { Route as AuthenticatedAgenciaAutomacoesAutomacaoIdRouteImport } from './routes/_authenticated/agencia.automacoes.$automacaoId'
import { Route as AuthenticatedClienteIndexRouteImport } from './routes/_authenticated/cliente.index'
import { Route as AuthenticatedClienteAprovacoesRouteImport } from './routes/_authenticated/cliente.aprovacoes'
import { Route as AuthenticatedClienteMetricasIndexRouteImport } from './routes/_authenticated/cliente.metricas.index'
import { Route as AuthenticatedClienteMetricasInstagramRouteImport } from './routes/_authenticated/cliente.metricas.instagram'
import { Route as AuthenticatedClienteMetricasMetaAdsRouteImport } from './routes/_authenticated/cliente.metricas.meta-ads'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAgenciaIndexRoute =
  AuthenticatedAgenciaIndexRouteImport.update({
    id: '/agencia/',
    path: '/agencia/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAgenciaClientesRoute =
  AuthenticatedAgenciaClientesRouteImport.update({
    id: '/agencia/clientes',
    path: '/agencia/clientes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAgenciaEquipeRoute =
  AuthenticatedAgenciaEquipeRouteImport.update({
    id: '/agencia/equipe',
    path: '/agencia/equipe',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAgenciaFluxoRoute =
  AuthenticatedAgenciaFluxoRouteImport.update({
    id: '/agencia/fluxo',
    path: '/agencia/fluxo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAgenciaVisualizarRoute =
  AuthenticatedAgenciaVisualizarRouteImport.update({
    id: '/agencia/visualizar',
    path: '/agencia/visualizar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAgenciaAutomacoesIndexRoute =
  AuthenticatedAgenciaAutomacoesIndexRouteImport.update({
    id: '/agencia/automacoes/',
    path: '/agencia/automacoes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAgenciaAutomacoesAutomacaoIdRoute =
  AuthenticatedAgenciaAutomacoesAutomacaoIdRouteImport.update({
    id: '/agencia/automacoes/$automacaoId',
    path: '/agencia/automacoes/$automacaoId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClienteIndexRoute =
  AuthenticatedClienteIndexRouteImport.update({
    id: '/cliente/',
    path: '/cliente/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClienteAprovacoesRoute =
  AuthenticatedClienteAprovacoesRouteImport.update({
    id: '/cliente/aprovacoes',
    path: '/cliente/aprovacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClienteMetricasIndexRoute =
  AuthenticatedClienteMetricasIndexRouteImport.update({
    id: '/cliente/metricas/',
    path: '/cliente/metricas/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClienteMetricasInstagramRoute =
  AuthenticatedClienteMetricasInstagramRouteImport.update({
    id: '/cliente/metricas/instagram',
    path: '/cliente/metricas/instagram',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClienteMetricasMetaAdsRoute =
  AuthenticatedClienteMetricasMetaAdsRouteImport.update({
    id: '/cliente/metricas/meta-ads',
    path: '/cliente/metricas/meta-ads',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agencia/clientes': typeof AuthenticatedAgenciaClientesRoute
  '/agencia/equipe': typeof AuthenticatedAgenciaEquipeRoute
  '/agencia/fluxo': typeof AuthenticatedAgenciaFluxoRoute
  '/agencia/visualizar': typeof AuthenticatedAgenciaVisualizarRoute
  '/agencia/automacoes/$automacaoId': typeof AuthenticatedAgenciaAutomacoesAutomacaoIdRoute
  '/cliente/aprovacoes': typeof AuthenticatedClienteAprovacoesRoute
  '/agencia/': typeof AuthenticatedAgenciaIndexRoute
  '/cliente/': typeof AuthenticatedClienteIndexRoute
  '/cliente/metricas/instagram': typeof AuthenticatedClienteMetricasInstagramRoute
  '/cliente/metricas/meta-ads': typeof AuthenticatedClienteMetricasMetaAdsRoute
  '/agencia/automacoes': typeof AuthenticatedAgenciaAutomacoesIndexRoute
  '/cliente/metricas/': typeof AuthenticatedClienteMetricasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agencia/clientes': typeof AuthenticatedAgenciaClientesRoute
  '/agencia/equipe': typeof AuthenticatedAgenciaEquipeRoute
  '/agencia/fluxo': typeof AuthenticatedAgenciaFluxoRoute
  '/agencia/visualizar': typeof AuthenticatedAgenciaVisualizarRoute
  '/agencia/automacoes/$automacaoId': typeof AuthenticatedAgenciaAutomacoesAutomacaoIdRoute
  '/cliente/aprovacoes': typeof AuthenticatedClienteAprovacoesRoute
  '/agencia': typeof AuthenticatedAgenciaIndexRoute
  '/cliente': typeof AuthenticatedClienteIndexRoute
  '/cliente/metricas/instagram': typeof AuthenticatedClienteMetricasInstagramRoute
  '/cliente/metricas/meta-ads': typeof AuthenticatedClienteMetricasMetaAdsRoute
  '/agencia/automacoes': typeof AuthenticatedAgenciaAutomacoesIndexRoute
  '/cliente/metricas': typeof AuthenticatedClienteMetricasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/agencia/clientes': typeof AuthenticatedAgenciaClientesRoute
  '/_authenticated/agencia/equipe': typeof AuthenticatedAgenciaEquipeRoute
  '/_authenticated/agencia/fluxo': typeof AuthenticatedAgenciaFluxoRoute
  '/_authenticated/agencia/visualizar': typeof AuthenticatedAgenciaVisualizarRoute
  '/_authenticated/agencia/automacoes/$automacaoId': typeof AuthenticatedAgenciaAutomacoesAutomacaoIdRoute
  '/_authenticated/cliente/aprovacoes': typeof AuthenticatedClienteAprovacoesRoute
  '/_authenticated/agencia/': typeof AuthenticatedAgenciaIndexRoute
  '/_authenticated/cliente/': typeof AuthenticatedClienteIndexRoute
  '/_authenticated/cliente/metricas/instagram': typeof AuthenticatedClienteMetricasInstagramRoute
  '/_authenticated/cliente/metricas/meta-ads': typeof AuthenticatedClienteMetricasMetaAdsRoute
  '/_authenticated/agencia/automacoes/': typeof AuthenticatedAgenciaAutomacoesIndexRoute
  '/_authenticated/cliente/metricas/': typeof AuthenticatedClienteMetricasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agencia/clientes'
    | '/agencia/equipe'
    | '/agencia/fluxo'
    | '/agencia/visualizar'
    | '/agencia/automacoes/$automacaoId'
    | '/cliente/aprovacoes'
    | '/agencia/'
    | '/cliente/'
    | '/cliente/metricas/instagram'
    | '/cliente/metricas/meta-ads'
    | '/agencia/automacoes'
    | '/cliente/metricas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agencia/clientes'
    | '/agencia/equipe'
    | '/agencia/fluxo'
    | '/agencia/visualizar'
    | '/agencia/automacoes/$automacaoId'
    | '/cliente/aprovacoes'
    | '/agencia'
    | '/cliente'
    | '/cliente/metricas/instagram'
    | '/cliente/metricas/meta-ads'
    | '/agencia/automacoes'
    | '/cliente/metricas'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/agencia/clientes'
    | '/_authenticated/agencia/equipe'
    | '/_authenticated/agencia/fluxo'
    | '/_authenticated/agencia/visualizar'
    | '/_authenticated/agencia/automacoes/$automacaoId'
    | '/_authenticated/cliente/aprovacoes'
    | '/_authenticated/agencia/'
    | '/_authenticated/cliente/'
    | '/_authenticated/cliente/metricas/instagram'
    | '/_authenticated/cliente/metricas/meta-ads'
    | '/_authenticated/agencia/automacoes/'
    | '/_authenticated/cliente/metricas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/agencia/': {
      id: '/_authenticated/agencia/'
      path: '/agencia'
      fullPath: '/agencia/'
      preLoaderRoute: typeof AuthenticatedAgenciaIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agencia/clientes': {
      id: '/_authenticated/agencia/clientes'
      path: '/agencia/clientes'
      fullPath: '/agencia/clientes'
      preLoaderRoute: typeof AuthenticatedAgenciaClientesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agencia/equipe': {
      id: '/_authenticated/agencia/equipe'
      path: '/agencia/equipe'
      fullPath: '/agencia/equipe'
      preLoaderRoute: typeof AuthenticatedAgenciaEquipeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agencia/fluxo': {
      id: '/_authenticated/agencia/fluxo'
      path: '/agencia/fluxo'
      fullPath: '/agencia/fluxo'
      preLoaderRoute: typeof AuthenticatedAgenciaFluxoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agencia/visualizar': {
      id: '/_authenticated/agencia/visualizar'
      path: '/agencia/visualizar'
      fullPath: '/agencia/visualizar'
      preLoaderRoute: typeof AuthenticatedAgenciaVisualizarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cliente/': {
      id: '/_authenticated/cliente/'
      path: '/cliente'
      fullPath: '/cliente/'
      preLoaderRoute: typeof AuthenticatedClienteIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cliente/aprovacoes': {
      id: '/_authenticated/cliente/aprovacoes'
      path: '/cliente/aprovacoes'
      fullPath: '/cliente/aprovacoes'
      preLoaderRoute: typeof AuthenticatedClienteAprovacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agencia/automacoes/': {
      id: '/_authenticated/agencia/automacoes/'
      path: '/agencia/automacoes'
      fullPath: '/agencia/automacoes'
      preLoaderRoute: typeof AuthenticatedAgenciaAutomacoesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agencia/automacoes/$automacaoId': {
      id: '/_authenticated/agencia/automacoes/$automacaoId'
      path: '/agencia/automacoes/$automacaoId'
      fullPath: '/agencia/automacoes/$automacaoId'
      preLoaderRoute: typeof AuthenticatedAgenciaAutomacoesAutomacaoIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cliente/metricas/': {
      id: '/_authenticated/cliente/metricas/'
      path: '/cliente/metricas'
      fullPath: '/cliente/metricas/'
      preLoaderRoute: typeof AuthenticatedClienteMetricasIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cliente/metricas/instagram': {
      id: '/_authenticated/cliente/metricas/instagram'
      path: '/cliente/metricas/instagram'
      fullPath: '/cliente/metricas/instagram'
      preLoaderRoute: typeof AuthenticatedClienteMetricasInstagramRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cliente/metricas/meta-ads': {
      id: '/_authenticated/cliente/metricas/meta-ads'
      path: '/cliente/metricas/meta-ads'
      fullPath: '/cliente/metricas/meta-ads'
      preLoaderRoute: typeof AuthenticatedClienteMetricasMetaAdsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAgenciaClientesRoute: typeof AuthenticatedAgenciaClientesRoute
  AuthenticatedAgenciaEquipeRoute: typeof AuthenticatedAgenciaEquipeRoute
  AuthenticatedAgenciaFluxoRoute: typeof AuthenticatedAgenciaFluxoRoute
  AuthenticatedAgenciaVisualizarRoute: typeof AuthenticatedAgenciaVisualizarRoute
  AuthenticatedAgenciaAutomacoesAutomacaoIdRoute: typeof AuthenticatedAgenciaAutomacoesAutomacaoIdRoute
  AuthenticatedClienteAprovacoesRoute: typeof AuthenticatedClienteAprovacoesRoute
  AuthenticatedAgenciaIndexRoute: typeof AuthenticatedAgenciaIndexRoute
  AuthenticatedClienteIndexRoute: typeof AuthenticatedClienteIndexRoute
  AuthenticatedClienteMetricasInstagramRoute: typeof AuthenticatedClienteMetricasInstagramRoute
  AuthenticatedClienteMetricasMetaAdsRoute: typeof AuthenticatedClienteMetricasMetaAdsRoute
  AuthenticatedAgenciaAutomacoesIndexRoute: typeof AuthenticatedAgenciaAutomacoesIndexRoute
  AuthenticatedClienteMetricasIndexRoute: typeof AuthenticatedClienteMetricasIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAgenciaClientesRoute: AuthenticatedAgenciaClientesRoute,
  AuthenticatedAgenciaEquipeRoute: AuthenticatedAgenciaEquipeRoute,
  AuthenticatedAgenciaFluxoRoute: AuthenticatedAgenciaFluxoRoute,
  AuthenticatedAgenciaVisualizarRoute: AuthenticatedAgenciaVisualizarRoute,
  AuthenticatedAgenciaAutomacoesAutomacaoIdRoute:
    AuthenticatedAgenciaAutomacoesAutomacaoIdRoute,
  AuthenticatedClienteAprovacoesRoute: AuthenticatedClienteAprovacoesRoute,
  AuthenticatedAgenciaIndexRoute: AuthenticatedAgenciaIndexRoute,
  AuthenticatedClienteIndexRoute: AuthenticatedClienteIndexRoute,
  AuthenticatedClienteMetricasInstagramRoute:
    AuthenticatedClienteMetricasInstagramRoute,
  AuthenticatedClienteMetricasMetaAdsRoute:
    AuthenticatedClienteMetricasMetaAdsRoute,
  AuthenticatedAgenciaAutomacoesIndexRoute:
    AuthenticatedAgenciaAutomacoesIndexRoute,
  AuthenticatedClienteMetricasIndexRoute:
    AuthenticatedClienteMetricasIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
